"""Write status, experiment, model, and data registries from verified upgrade evidence."""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def main() -> None:
 reports=ROOT/'reports'; reports.mkdir(exist_ok=True)
 synth=json.loads((reports/'experiments'/'synthetic-gate-benchmark.json').read_text()); v2=json.loads((reports/'experiments'/'county-panel-v2.json').read_text()); v2model=json.loads((reports/'experiments'/'county-v2-weather-models.json').read_text()); external=json.loads((reports/'experiments'/'external-domain-eia.json').read_text()); route=json.loads((reports/'final_route_scorecard.json').read_text())
 (ROOT/'STATUS.md').write_text(f'''# Upgrade Status\n\n- Dataset V1: `FROZEN_AND_VERIFIED`\n- Synthetic fidelity-gate benchmark: `{synth['status']}`\n- Applied V1 decision support: `GUARDED_ABSTAIN_ONLY`\n- Dataset V2 yield/weather panel: `{v2['status']}`\n- Dataset V2 locked temporal experiment: `{v2model['status']}`; explanation `{v2model['explanation_availability']}`\n- External-domain validation: `{external['status']}`\n- Paper route: `{route['selected_route']}` (`{route['status']}`)\n\nNo agricultural model is promoted as a predictive or explanatory champion.\n''')
 (reports/'progress_log.md').write_text(f'''# Progress Log\n\n- Phase 0: path validation, DOCX extraction, inventory PASS.\n- Phase 1: Dataset V1 frozen and hash-verified.\n- Phase 2: synthetic ground-truth benchmark PASS; V1 queue guarded by failed gates.\n- Dataset V2: NASS county wheat raw responses, canonical panel, Census centroids, and NASA POWER weather coverage PASS.\n- Dataset V2 locked experiment: validation selected `{v2model['selected_on_validation']}`; holdout Gate A remains inconclusive, so explanation is `{v2model['explanation_availability']}`.\n- External EIA feature-group validation: `{external['status']}`.\n''')
 (reports/'model_registry.csv').write_text(f'''model_id,status,selection_basis,holdout_status,claim\nv1_extra_trees_weather_only,SENSITIVITY_ONLY,2012-2015 validation,Gate A FAIL; Gate B1 FAIL,not eligible for explanation or promotion\nsynthetic_full_gate,METHOD_EVIDENCE,pre-registered synthetic scenarios,PASS,reduces simulated false permission; not an agricultural predictor\nv2_{v2model['selected_on_validation']},{v2model['status']},locked validation RMSE,Gate A CI crosses zero; Gate B1 cannot promote unselected weather-only model,no agricultural predictive or weather-specific explanation claim\n''')
 (reports/'data_registry.csv').write_text('dataset_id,status,scope,evidence\nv1_state_panel,FROZEN,State-Level Crop-Yield Panel,data/legacy/state_panel_v1/V1_IMMUTABLE_MANIFEST.json\nv2_county,PANEL_AND_WEATHER_PASS,County-Level Winter Wheat residual panel (574 counties; 2000-2025),reports/experiments/county-panel-v2.json; reports/v2/weather_feature_coverage.json\n')
 print('Upgrade registries written')
if __name__=='__main__': main()
